### ISSUE TITLE
Not showing events without `LOCATION` property and same event shown multiple times

### ISSUE THREAD

**Issue by ramonsmits** [larrybolt/online-ics-feed-viewer#1]
The following ICS file was not loaded without `LOCATION`  properties.

- http://static.exyll.net/exports/bevelvoerder.ics

After adding the LOCATION property the same event is shown multiple times

![image](https://user-images.githubusercontent.com/152998/56137646-9967e700-5f95-11e9-8838-42bef805038f.png)

The current content is:
```ics
BEGIN:VCALENDAR
VERSION:2.0
X-ORIGINAL-URL:http://static.exyll.net/exports/bevelvoerder.ics
X-WR-CALNAME:Bevelvoerder
METHOD:PUBLISH
PRODID:static.exyll.net
BEGIN:VEVENT
LOCATION:Hoogvliet
SUMMARY:Onderbezetting - bevelvoerder
UID:b9165cec41eb3e16b0b115df740c8e31
DTSTART;VALUE=DATE-TIME:20190409T050000Z
DTEND;VALUE=DATE-TIME:20190409T060000Z
DTSTAMP:20190415T132835Z
CATEGORIES:Onderbezetting
END:VEVENT
BEGIN:VEVENT
LOCATION:Hoogvliet
SUMMARY:Onderbezetting - bevelvoerder
UID:83a329fa239930f784430ead5325e589
DTSTART;VALUE=DATE-TIME:20190411T050000Z
DTEND;VALUE=DATE-TIME:20190411T060000Z
DTSTAMP:20190415T132835Z
CATEGORIES:Onderbezetting
END:VEVENT
BEGIN:VEVENT
LOCATION:Hoogvliet
SUMMARY:Onderbezetting - bevelvoerder
UID:4e33773a399a3042864d6b0b3727e672
DTSTART;VALUE=DATE-TIME:20190418T050000Z
DTEND;VALUE=DATE-TIME:20190418T060000Z
DTSTAMP:20190415T132835Z
CATEGORIES:Onderbezetting
END:VEVENT
END:VCALENDAR
```

**Comment by larrybolt** [comment]
@ramonsmits I'm so sorry, I think github didn't send me a notification :( I'll look into this over the next few days!

**Comment by larrybolt** [comment]
It seems to be working now though:
https://larrybolt.github.io/online-ics-feed-viewer/#feed=http%3A//static.exyll.net/exports/bevelvoerder.ics&cors=true&title=My%20Feed&hideinput=false
<img width="709" alt="Screen Shot 2020-04-13 at 03 06 08" src="https://user-images.githubusercontent.com/803296/79086387-c4655200-7d33-11ea-8259-7ee147969c61.png">
